[package]
name = "pl0"
version = "0.1.0"
authors = ["qiufeng"]
description = "A simple intepreter/compiler for pl0"
edition = "2021"
license = "MIT"

[lib]
name = "pl0"
path = "src/lib.rs"

[dependencies]
thiserror = "1"
